#ifndef MAPPING_H
#define MAPPING_H

#define PIN_DRIVE_LEFT_PWM 11
#define PIN_DRIVE_LEFT_IN1 36
#define PIN_DRIVE_LEFT_IN2 34

#define PIN_DRIVE_RIGHT_PWM 9
#define PIN_DRIVE_RIGHT_IN1 45
#define PIN_DRIVE_RIGHT_IN2 47

#define PIN_ENCODER_LEFT_A 3
#define PIN_ENCODER_LEFT_B 5
#define PIN_ENCODER_RIGHT_A 2
#define PIN_ENCODER_RIGHT_B 4

#define PIN_SWITCH_LATCH_1 7
#define PIN_SWITCH_LATCH_2 7
#define PIN_MOTOR_LATCH_EN 11
#define PIN_MOTOR_LATCH_IN1 13
#define PIN_MOTOR_LATCH_IN2 12

//#define PIN_MOTOR_CATAPULT_EN 9
//#define PIN_MOTOR_CATAPULT_IN1 8
//#define PIN_MOTOR_CATAPULT_IN2 10

#define PIN_SERVO_LOAD 3

/* No longer used
#define PIN_DEBUG_LED_1 10
#define PIN_DEBUG_LED_2 9
#define PIN_DEBUG_LED_3 8
#define PIN_DEBUG_LED_4 7
*/

#endif
