#ifndef MAPPING_H
#define MAPPING_H

#define PIN_DRIVE_LEFT_EN 3
#define PIN_DRIVE_LEFT_IN1 8
#define PIN_DRIVE_LEFT_IN2 9
#define PIN_DRIVE_RIGHT_EN 4
#define PIN_DRIVE_RIGHT_IN1 10
#define PIN_DRIVE_RIGHT_IN2 11

#define PIN_ENCODER_LEFT_A 0
#define PIN_ENCODER_LEFT_B 0
#define PIN_ENCODER_RIGHT_A 0
#define PIN_ENCODER_RIGHT_B 0

#define PIN_DEBUG_LED_1 10
#define PIN_DEBUG_LED_2 9
#define PIN_DEBUG_LED_3 8
#define PIN_DEBUG_LED_4 7

#endif